# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 043e33c9369e7662898fb10b9afd83d8b53c14c7c97b13fbba77da9e7be8abf63f48f41e4642e7efd70e02000f6021145406fffc1e917c5e4a6cceeb5bd5cff0

test:
  secret_key_base: b9a68cf4f187da81f58f6fe049bb8fb75419e218773d945662e76d65017b2f19aee166e93655b60a157f9198f772724a2008456c2dde5fcbf214e1f3e626ad2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
